import Head from "next/head";
import { AuthenticatedActionsProvider } from "../components/AuthenticatedActionsProvider";
import { UnauthenticatedActions } from "../components/UnauthenticatedActions";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";
import { Hero } from "@web3uikit/core";
import {COLORS, isSupportedChainId} from '../utils';

export default function Home() {
  const { isWeb3Enabled, account, web3} = useMoralis();
  const renderAuthenticatedContent = isWeb3Enabled && account;
  const chainId: number | undefined = web3?.network?.chainId;

  return (
    <div className={styles.container}>
      <Head>
        <title>VRF Magic 8 Ball</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Hero
          align="right"
          rounded="0px"
          textColor={COLORS.white}
          title="The World's First Verifiably Random Magic 8 Ball"
          backgroundColor={COLORS.biscay}
        />
      </header>

      <main className={styles.main}>
        {renderAuthenticatedContent ? (
          <AuthenticatedContent account={account} chainId={chainId} />
        ) : (
          <UnauthenticatedActions />
        )}
      </main>

      <footer className={styles.footer}>
        <div>Made by James Boyle</div>
      </footer>
    </div>
  );
}

interface AuthenticatedContentProps {
  chainId?: number;
  account: string;
}

function AuthenticatedContent(props: AuthenticatedContentProps) {
  const { chainId, account } = props;
  const supportedChainId = chainId && isSupportedChainId(chainId);
  if (supportedChainId) {
    return <AuthenticatedActionsProvider account={account} />;
  } else {
    return <div>Chain is not supported</div>;
  }
}
