import Head from "next/head";
import {AuthenticatedActionsProvider} from '../components/AuthenticatedActionsProvider';
import { UnauthenticatedActions } from "../components/UnauthenticatedActions";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { isWeb3Enabled, account } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>TODO title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isWeb3Enabled && account ? (
          <AuthenticatedActionsProvider account={account} />
        ) : (
          <UnauthenticatedActions />
        )}
      </main>

      <footer className={styles.footer}>TODO footer.</footer>
    </div>
  );
}
